package me.novascomp.utils.standalone.attributes;

public enum AttributeTag {
    USER_CRUD_CREATE,
    USER_CRUD_UPDATE,
    TOKEN_CRUD_CREATE,
    TOKEN_CRUD_UPDATE,
    SCOPE_CRUD_CREATE,
    SCOPE_CRUD_UPDATE,
    ORGANIZATION_CRUD_CREATE,
    ORGANIZATION_CRUD_UPDATE,
    FLAT_CRUD_CREATE,
    FLAT_CRUD_UPDATE,
    DETAIL_CRUD_CREATE,
    DETAIL_CRUD_UPDATE,
    RESIDENT_CRUD_CREATE,
    RESIDENT_CRUD_UPDATE,
    MESSAGE_RECORD_NVM_CREATE,
    MESSAGE_RECORD_NVM_UPDATE;
}
